name: Waka Readme

on:
  schedule:
    # Runs at 12am UTC
    - cron: '0 12 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_UPDATED_DATE: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROJECTS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_TIMEZONE: "False"
          SHOW_LOC_CHART: "False"
