# https://github.com/anmol098/waka-readme-stats
name: Wakatime README
on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_SHORT_INFO: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_PROJECTS: "False"
          SHOW_COMMIT: "False"
          SHOW_UPDATED_DATE: "True"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_LOC_CHART: "False"
